// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CopyConstructorGenerator2022
{
    internal sealed partial class Vsix
    {
        public const string Id = "CopyConstructorGenerator2022.be44d44e-ad92-415d-9a25-c5bbc052676d";
        public const string Name = "CopyConstructorGenerator2022";
        public const string Description = @"コピーコンストラクタを作成します。";
        public const string Language = "ja-JP";
        public const string Version = "1.0";
        public const string Author = "kttFox";
        public const string Tags = "";
    }
}
